"""
generate_document — produces .docx or .pptx from financial analysis content.
Files saved to /tmp/generated/ and served via /files/{filename} FastAPI route.
"""
from __future__ import annotations

import os
import uuid
import base64
import logging
from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)

OUTPUT_DIR = os.getenv("GENERATED_DIR", "/tmp/generated")
os.makedirs(OUTPUT_DIR, exist_ok=True)


class Section(BaseModel):
    heading: str
    body:    str


class GenerateDocRequest(BaseModel):
    doc_type:  Literal["word", "ppt"] = Field(default="word")
    title:     str = Field(min_length=1, max_length=200)
    subtitle:  str = Field(default="")
    sections:  list[Section] = Field(default_factory=list)
    author:    str = Field(default="AmexInsight Agent")


class GenerateDocResponse(BaseModel):
    success:     bool
    filename:    str = ""
    url:         str = ""
    content_b64: str = ""   # base64-encoded file bytes for email attachment
    error:       str = ""


def _make_word(req: GenerateDocRequest, filename: str) -> str:
    from docx import Document
    from docx.shared import Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = Document()

    # Title
    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title_para.add_run(req.title)
    run.bold = True
    run.font.size = Pt(22)
    run.font.color.rgb = RGBColor(0x00, 0x6F, 0xCE)  # AMEX blue

    # Subtitle / date
    sub = req.subtitle or f"Generated by AmexInsight · {datetime.utcnow().strftime('%B %d, %Y')}"
    sub_para = doc.add_paragraph(sub)
    sub_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub_para.runs[0].font.size = Pt(11)
    sub_para.runs[0].font.color.rgb = RGBColor(0x66, 0x66, 0x66)

    doc.add_paragraph()  # spacer

    # Sections
    for section in req.sections:
        h = doc.add_heading(section.heading, level=2)
        h.runs[0].font.color.rgb = RGBColor(0x00, 0x6F, 0xCE)
        doc.add_paragraph(section.body)
        doc.add_paragraph()

    # Footer note
    footer = doc.add_paragraph(
        f"Source: AmexInsight MCP · BM25+FTS5+CrossEncoder retrieval · "
        f"Author: {req.author} · {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}"
    )
    footer.runs[0].font.size = Pt(8)
    footer.runs[0].font.color.rgb = RGBColor(0x99, 0x99, 0x99)

    path = os.path.join(OUTPUT_DIR, filename)
    doc.save(path)
    return path


def _make_ppt(req: GenerateDocRequest, filename: str) -> str:
    from pptx import Presentation
    from pptx.util import Inches, Pt
    from pptx.dml.color import RGBColor

    prs = Presentation()
    BLUE = RGBColor(0x00, 0x6F, 0xCE)
    WHITE = RGBColor(0xFF, 0xFF, 0xFF)
    DARK = RGBColor(0x1A, 0x1A, 0x2E)

    # ── Title slide ──────────────────────────────────────────────────────────
    title_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_layout)
    slide.shapes.title.text = req.title
    slide.shapes.title.text_frame.paragraphs[0].runs[0].font.bold = True
    slide.shapes.title.text_frame.paragraphs[0].runs[0].font.color.rgb = BLUE

    sub_tf = slide.placeholders[1].text_frame
    sub_tf.text = req.subtitle or f"AmexInsight · {datetime.utcnow().strftime('%B %Y')}"
    sub_tf.paragraphs[0].runs[0].font.size = Pt(18)

    # ── Content slides ───────────────────────────────────────────────────────
    content_layout = prs.slide_layouts[1]
    for section in req.sections:
        sl = prs.slides.add_slide(content_layout)
        sl.shapes.title.text = section.heading
        sl.shapes.title.text_frame.paragraphs[0].runs[0].font.color.rgb = BLUE
        sl.shapes.title.text_frame.paragraphs[0].runs[0].font.bold = True

        body_tf = sl.placeholders[1].text_frame
        body_tf.text = ""
        # Split body into bullet points on newlines or ". "
        lines = [l.strip() for l in section.body.replace(". ", ".\n").split("\n") if l.strip()]
        for i, line in enumerate(lines[:8]):  # max 8 bullets per slide
            p = body_tf.add_paragraph() if i > 0 else body_tf.paragraphs[0]
            p.text = line
            p.level = 0
            run = p.runs[0] if p.runs else p.add_run()
            run.font.size = Pt(16)

    # ── Last slide — source attribution ─────────────────────────────────────
    end_layout = prs.slide_layouts[5]
    end_slide = prs.slides.add_slide(end_layout)
    txBox = end_slide.shapes.add_textbox(Inches(1), Inches(2.5), Inches(8), Inches(2))
    tf = txBox.text_frame
    tf.text = "Generated by AmexInsight"
    tf.paragraphs[0].runs[0].font.size = Pt(24)
    tf.paragraphs[0].runs[0].font.bold = True
    tf.paragraphs[0].runs[0].font.color.rgb = BLUE

    p2 = tf.add_paragraph()
    p2.text = f"BM25 + FTS5 + Cross-Encoder retrieval · {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}"
    p2.runs[0].font.size = Pt(12)
    p2.runs[0].font.color.rgb = RGBColor(0x66, 0x66, 0x66)

    path = os.path.join(OUTPUT_DIR, filename)
    prs.save(path)
    return path


async def generate_document(req: GenerateDocRequest) -> GenerateDocResponse:
    ext = "docx" if req.doc_type == "word" else "pptx"
    uid = uuid.uuid4().hex[:8]
    safe_title = "".join(c for c in req.title if c.isalnum() or c in " -_")[:40].strip().replace(" ", "_")
    filename = f"{safe_title}_{uid}.{ext}"

    try:
        if req.doc_type == "word":
            _make_word(req, filename)
        else:
            _make_ppt(req, filename)

        base_url = os.getenv("MCP_BASE_URL", "https://mcp-v2-h4axdpfmgqa2htbk.canadacentral-01.azurewebsites.net")
        url = f"{base_url}/files/{filename}"

        # Read file and base64-encode for email attachment
        file_path = os.path.join(OUTPUT_DIR, filename)
        with open(file_path, "rb") as f:
            content_b64 = base64.b64encode(f.read()).decode()

        logger.info(f"[generate_document] {ext} created: {filename}")
        return GenerateDocResponse(success=True, filename=filename, url=url, content_b64=content_b64)

    except Exception as e:
        import traceback
        logger.error(f"[generate_document] failed: {e}\n{traceback.format_exc()}")
        return GenerateDocResponse(success=False, error=f"{type(e).__name__}: {e}")
